classDiagram

    %% Controller
    class SpringbootBasicApplication
    class ConsoleApplication
    SpringbootBasicApplication --> ConsoleApplication
    ConsoleApplication --> ConsoleManager

    %% IO
    class ConsoleManager
    class InputConsole
    class OutputConsole
    ConsoleManager --> InputConsole
    ConsoleManager --> OutputConsole

    %% Controller
    class VoucherController
    class CustomerController
    class WalletController
    ConsoleApplication --> VoucherController : VoucherDto
    ConsoleApplication --> CustomerController : CustomerDto
    ConsoleApplication --> WalletController

    %% Service
    class VoucherService
    class CustomerService
    VoucherController --> VoucherService : Voucher
    CustomerController --> CustomerService : Customer
    WalletController --> WalletService

    %% Repository
    class VoucherRepository {
        <<interface>>
    }
    VoucherService --> VoucherRepository
    class MemoryVoucherRepository
    MemoryVoucherRepository --> VoucherMap
    class JdbcVoucherRepository
    JdbcVoucherRepository --> vouchers
    VoucherRepository <.. MemoryVoucherRepository
    VoucherRepository <.. JdbcVoucherRepository

    class WalletRepository {
        <<interface>>
    }
    WalletService --> WalletRepository
    WalletRepository <.. JdbcWalletRepository
    JdbcWalletRepository --> vouchers
    JdbcWalletRepository --> customers

    class CustomerRepository {
        <<interface>>
    }
    CustomerService --> CustomerRepository
    class JdbcCustomerRepository
    CustomerRepository <.. JdbcCustomerRepository
    JdbcCustomerRepository --> customers