classDiagram

    %% Controller
    class SpringbootBasicApplication
    class ConsoleApplication
    SpringbootBasicApplication --> ConsoleApplication
    ConsoleApplication --> ConsoleManager

    %% IO
    class ConsoleManager
    class InputConsole
    class OutputConsole
    ConsoleManager --> InputConsole
    ConsoleManager --> OutputConsole

    class VoucherController
    class CustomerController
    ConsoleApplication --> VoucherController : VoucherDto
    ConsoleApplication --> CustomerController : CustomerDto

    %% Service
    class VoucherService
    class CustomerService
    VoucherController --> VoucherService : Voucher
    CustomerController --> CustomerService : Customer

    %% Repository
    class VoucherRepository {
        <<interface>>
    }
    VoucherService --> VoucherRepository
    class MemoryVoucherRepository
    class JdbcVoucherRepository
    JdbcVoucherRepository --> CsvReader
    VoucherRepository <.. MemoryVoucherRepository
    VoucherRepository <.. JdbcVoucherRepository

    class CustomerRepository
    CustomerRepository --> CsvReader
    CustomerService --> CustomerRepository
