flowchart LR
    start_node[Start] --> menu{Menu}
    menu -- EXIT --> end_node[End]
    menu -- REGISTER_CUSTOMER --> RegisterCustomer[Register Customer]
    menu -- UNREGISTER_CUSTOMER --> UnregisterCustomer[Unregister Customer]
    menu -- LIST_ALL_CUSTOMERS --> ListCustomer[List Customers]
    menu -- REGISTER_VOUCHER_TO_CUSTOMER --> RegisterVoucher[Register Voucher]
    menu -- UNREGISTER_VOUCHER_FROM_CUSTOMER --> UnregisterVoucher[Unregister Voucher]
    menu -- LIST_VOUCHERS_OF_CUSTOMER --> ListVoucher[List Voucher of Customer]
    menu -- LIST_BLACK_CUSTOMERS --> ListBlackCustomer[List Black Customers]