spring:
  datasource:
    url: jdbc:mysql://localhost:3306/voucher?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Seoul
    username: voucher
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
