datasource:
  url: jdbc:mysql://localhost:3305/voucher_management
  username: root
  password: 1234

file:
  resources:
    path: src/main/resources/
    build-path: /resources/main/

  domains:
    customer:
      csv-file-name: blacklist.csv
