DROP TABLE IF EXISTS voucher.CUSTOMERS;
CREATE TABLE voucher.CUSTOMERS
(
    CUSTOMER_ID VARCHAR(50) PRIMARY KEY,
    NAME VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL UNIQUE ,
    LAST_LOGIN_AT DATETIME(6) DEFAULT NULL,
    CREATED_AT DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
) DEFAULT CHARSET=UTF8MB4;

DROP TABLE IF EXISTS voucher.VOUCHERS;
CREATE TABLE voucher.VOUCHERS
(
    VOUCHER_ID VARCHAR(50) PRIMARY KEY,
    VOUCHER_TYPE VARCHAR(20) NOT NULL,
    AMOUNT INT UNSIGNED NOT NULL DEFAULT 0,
    CUSTOMER_ID VARCHAR(50) UNIQUE,
    CREATED_AT DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    INDEX FK_CUSTOMER_ID (CUSTOMER_ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES voucher.VOUCHERS (CUSTOMER_ID)
        ON UPDATE CASCADE ON DELETE CASCADE
) DEFAULT CHARSET=UTF8MB4;