DROP TABLE IF EXISTS voucher.CUSTOMERS;
CREATE TABLE voucher.CUSTOMERS
(
    CUSTOMER_ID VARCHAR(50) PRIMARY KEY,
    NAME VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL UNIQUE ,
    LAST_LOGIN_AT DATETIME(6) DEFAULT NULL,
    CREATED_AT DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
) DEFAULT CHARSET=UTF8MB4;

DROP TABLE IF EXISTS voucher.VOUCHERS;
CREATE TABLE voucher.VOUCHERS
(
    VOUCHER_ID VARCHAR(50) PRIMARY KEY,
    VOUCHER_TYPE VARCHAR(20) NOT NULL,
    AMOUNT INT UNSIGNED NOT NULL DEFAULT 0,
    CREATED_AT DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
) DEFAULT CHARSET=UTF8MB4;

DROP TABLE IF EXISTS voucher.WALLET;
CREATE TABLE voucher.WALLET
(
    VOUCHER_ID VARCHAR(50) NOT NULL,
    CUSTOMER_ID VARCHAR(50) NOT NULL,
    INDEX FK_CUSTOMER_ID (CUSTOMER_ID),
    INDEX FK_VOUCHER_ID (VOUCHER_ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES voucher.CUSTOMERS (CUSTOMER_ID)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (VOUCHER_ID) REFERENCES voucher.VOUCHERS (VOUCHER_ID)
        ON UPDATE CASCADE ON DELETE CASCADE
)