DROP TABLE IF EXISTS voucher;
DROP TABLE IF EXISTS customer;

CREATE TABLE voucher (
    id VARCHAR(36) PRIMARY KEY,
    type VARCHAR(5) NOT NULL,
    discount_amount INTEGER NOT NULL
);

CREATE TABLE customer (
    id VARCHAR(36) PRIMARY KEY,
    type VARCHAR(5) NOT NULL,
    nickname VARCHAR(255) UNIQUE NOT NULL
)