CREATE TABLE CUSTOMER
(
    CUSTOMER_ID   BIGINT PRIMARY KEY,
    NAME          varchar(20) NOT NULL,
    EMAIL         varchar(50) NOT NULL,
    LAST_LOGIN_AT datetime(6)          DEFAULT NULL,
    SIGNED_UP_AT  datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    CONSTRAINT unq_user_email UNIQUE (email)
);
CREATE TABLE VOUCHER
(
    VOUCHER_ID  BINARY(16) PRIMARY KEY,
    AMOUNT      INTEGER NOT NULL,
    TYPE        VARCHAR NOT NULL,
    CUSTOMER_ID BIGINT,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (CUSTOMER_ID)
);
