DROP SEQUENCE IF EXISTS MEMBER_SEQ;
DROP TABLE IF EXISTS MEMBER;
DROP TABLE IF EXISTS VOUCHER;

CREATE SEQUENCE MEMBER_SEQ;

CREATE TABLE MEMBER
(
    MEMBER_ID     BIGINT      DEFAULT MEMBER_SEQ.nextval PRIMARY KEY,
    NAME          varchar(20) NOT NULL,
    EMAIL         varchar(50) NOT NULL,
    LAST_LOGIN_AT timestamp(7) DEFAULT NULL,
    SIGNED_UP_AT  timestamp(7) NOT NULL,
    CONSTRAINT EMAIL UNIQUE (email)
);
CREATE TABLE VOUCHER
(
    VOUCHER_ID BINARY(16) PRIMARY KEY,
    AMOUNT     INTEGER     NOT NULL,
    TYPE       VARCHAR(10) NOT NULL,
    MEMBER_ID  BIGINT DEFAULT NULL,
    REGISTERED_AT  timestamp(7) NOT NULL,
    FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID) ON DELETE SET NULL
);