black-list:
  csv-file-name: customer_blacklist.csv
  path: src\main\resources\customer_blacklist.csv

spring:
  datasource:
    url: jdbc:mysql://localhost/kdt_voucher
    username:
    password:

---

spring:
  config:
    activate:
      on-profile: prod
voucher:
  file-name: vouchers.csv
  path: src\main\resources\vouchers.csv


---