/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.programmers.order;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.Bean;

import com.programmers.order.controller.Controller;
import com.programmers.order.controller.ControllerManager;
import com.programmers.order.io.Input;
import com.programmers.order.message.BasicMessage;
import com.programmers.order.type.ProgramType;

@SpringBootApplication
public class App {
	private static final Logger logger = LoggerFactory.getLogger(App.class);

	private final Input input;
	private final ControllerManager controllerManager;

	public App(Input input, ControllerManager controllerManager) {
		this.input = input;
		this.controllerManager = controllerManager;
	}

	public static void main(String[] args) {
		SpringApplication.run(App.class, args);
	}

	@Bean
	public CommandLineRunner commandLineRunner(ApplicationContext applicationContext) {
		logger.info("voucher management system start !");
		return args -> {
			ProgramType program = ProgramType.NONE;
			do {
				String programType = input.read(BasicMessage.CommonMessage.PROGRAM_INIT);
				program = ProgramType.of(programType);
				Controller controller = controllerManager.of(program.getBeanName());

				controller.run();
			} while (program.isNotExit());
		};

	}
}
