/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.programmers.order;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.Bean;

import com.programmers.order.controller.VoucherController;

@SpringBootApplication
public class App {
	private static final Logger logger = LoggerFactory.getLogger(App.class);

	private final VoucherController voucherController;

	public App(VoucherController voucherController) {
		this.voucherController = voucherController;
	}

	public static void main(String[] args) {
		SpringApplication.run(App.class, args);
	}

	@Bean
	public CommandLineRunner commandLineRunner(ApplicationContext applicationContext) {
		logger.info("voucher management system start !");
		return args -> {
			voucherController.run();
		};
	}
}
