INSERT INTO CUSTOMER
VALUES (1, "normal");
INSERT INTO CUSTOMER
VALUES (2, "normal");
INSERT INTO CUSTOMER
VALUES (3, "normal");

INSERT INTO VOUCHER
VALUES (1, "fixed", 10);
INSERT INTO VOUCHER
VALUES (2, "fixed", 100);
INSERT INTO VOUCHER
VALUES (3,"fixed", 1000);


INSERT INTO CUSTOMER_VOUCHER
VALUES(1, 1, 1);
INSERT INTO CUSTOMER_VOUCHER
VALUES(2, 1, 2);
INSERT INTO CUSTOMER_VOUCHER
VALUES(3, 1, 3);