drop table if exists customer CASCADE;

create table customer
(
    id            bigint generated by default as identity,
    customer_name varchar(30) not null,
    primary key (id),
    unique (customer_name)
);

create table voucher
(
    voucher_id        varchar(50),
    voucher_type      varchar(30) not null,
    discount_level    bigint,
    created_date_time timestamp,
    primary key (voucher_id)
);