drop table if exists customer CASCADE;

create table customer
(
    id            bigint generated by default as identity,
    customer_name varchar(30) not null,
    primary key (id),
    unique (customer_name)
);

create table vouchers
(
    uuid          varchar(50),
    voucher_type  varchar(30) not null,
    amount        bigint,
    ratio         bigint,
    customer_name varchar(30) not null,
    primary key (uuid),
    foreign key (customer_name) references customer (customer_name)
);